site_name: Big Data
site_url: https://aitor-medrano.github.io
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "Arquitecturas Big Data":
      - "1.- Arquitecturas": "apuntes/arquitecturas01.md"
      - "2.- Cloud Computing": "apuntes/arquitecturas02.md"
      - "3.- AWS": "apuntes/arquitecturas03.md"
      - "4.- AWS EC2": "apuntes/arquitecturas04.md"
      - "5.- AWS S3": "apuntes/arquitecturas05.md"
      - "6.- Azure": "apuntes/arquitecturas06.md"
  - "Ingesta de Datos":
      - "1.- ETL": "ejercicios/index.md"
      - "2.- ETL con SQL/Python": "ejercicios/index.md"
      - "3.- Pentaho": "ejercicios/index.md"
      - "4.- Pentaho multidimensional": "ejercicios/index.md"
      - "5.- Nifi I": "ejercicios/index.md"
      - "6.- Nifi II": "ejercicios/index.md"
  - "Big Data Aplicado":
      - "1.- Hadoop": "apuntes/bdaplicado01.md"
      - "2.- HDFS": "ejercicios/index.md"
      - "3.- Hive": "ejercicios/index.md"
      - "4.- Flume / Sqoop": "ejercicios/index.md"
      - "5.- Kafka": "ejercicios/index.md"
      - "6.- Spark":
          - "6.1.-Trabajando con Spark": "apuntes/bdaplicado0601.md"
          - "6.2.-Spark RDD": "ejercicios/index.md"
          - "6.3.-Spark Avanzado": "ejercicios/index.md"
          - "6.4.-Spark SQL": "ejercicios/index.md"
          - "6.5.-Spark Streaming I": "ejercicios/index.md"
          - "6.6.-Spark Streaming II": "ejercicios/index.md"

theme:
  language: es
  name: "material"
  palette:
    primary: light blue
    accent: "Teal"
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logo.jpg"
  features:
    - header.autohide

extra:
  search:
    language: "en"
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aitormedrano

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: Copyright &copy; 2021 Aitor Medrano
# docker run --name=mkdocs -v "C:\Users\Aitor\OneDrive - Conselleria d'Educació\2122\bigdata:/app" -w /app/doc -p 8000:8000 minidocks/mkdocs serve -a 0.0.0.0:8000 -t material
# docker run --name=mkdocs -v "C:\Users\Aitor\OneDrive - Conselleria d'Educació\2122\bigdata:/app" -w /app/mkdocs -p 8000:8000 minidocks/mkdocs serve -a 0.0.0.0:8000 -t material
