site_name: Inteligencia Artificial y Big Data
site_url: https://aitor-medrano.github.io/bigdata2122
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "Arquitecturas Big Data":
      - "1.- Cloud Computing": "apuntes/nube01.md"
      - "2.- AWS": "apuntes/nube02aws.md"
      - "3.- Computación": "apuntes/nube03computacion.md"
      - "4.- Almacenamiento": "apuntes/nube04almacenamiento.md"
      - "5.- Datos": "apuntes/nube05datos.md"
      - "6.- Arquitecturas": "apuntes/arquitecturas01.md"
  - "Ingesta de Datos":
      - "1.- ETL": "apuntes/ingesta01.md"
  #     - "2.- ETL con SQL/Python": "apuntes/ingesta02.md"
  #     - "3.- Pentaho": "apuntes/ingesta03.md"
  #     - "4.- Pentaho multidimensional": "apuntes/ingesta04.md"
  #     - "5.- Nifi I": "apuntes/ingesta05.md"
  #     - "6.- Nifi II": "apuntes/ingesta06.md"
  # - "Big Data Aplicado":
  #     - "1.- Hadoop": "apuntes/bdaplicado01.md"
  #     - "2.- HDFS": "apuntes/bdaplicado02.md"
  #     - "3.- Hive": "apuntes/bdaplicado03.md"
  #     - "4.- Flume / Sqoop": "apuntes/bdaplicado04.md"
  #     - "5.- Kafka": "apuntes/bdaplicado05.md"
  #     - "6.- Spark":
  #         - "6.1.-Trabajando con Spark": "apuntes/bdaplicado0601.md"
  #         - "6.2.-Spark RDD": "apuntes/bdaplicado0602.md"
  #         - "6.3.-Spark Avanzado": "apuntes/bdaplicado0603.md"
  #         - "6.4.-Spark SQL": "apuntes/bdaplicado0604.md"
  #         - "6.5.-Spark Streaming I": "apuntes/bdaplicado0605.md"
  #         - "6.6.-Spark Streaming II": "apuntes/bdaplicado0606.md"
  #     - "Ejercicios": "ejercicios/ej-bdaplicado.md"

theme:
  language: es
  name: "material"
  favicon: "imagenes/favicon.png"
  palette:
    primary: light blue
    accent: "Teal"
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logoIABD3.png"
  features:
    - header.autohide
    - navigation.top
    - navigation.tracking
    - content.code.annotate

extra:
  search:
    language: "en"
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aitormedrano
    - icon: fontawesome/solid/envelope-square
      link: mailto:<a.medrano@edu.gva.es>
  analytics:
    provider: google
    property: G-MV889H0W63

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2021-2022 Aitor Medrano - Licencia CC BY-NC-SA
# docker run --name=mkdocs -v "C:\Users\Aitor\OneDrive - Conselleria d'Educació\2122\bigdata:/app" -w /app/doc -p 8000:8000 minidocks/mkdocs serve -a 0.0.0.0:8000 -t material
# docker run --name=mkdocs -v "C:\Users\Aitor\OneDrive - Conselleria d'Educació\2122\bigdata:/app" -w /app/mkdocs -p 8000:8000 minidocks/mkdocs serve -a 0.0.0.0:8000 -t material
